lang: ja-JP
title: 食事と睡眠
theme: jekyll-theme-minimal

webrick:
  headers:
    My-Header: My-Value
    My-Other-Header: My-Other-Value

sidebar:
  - title: "Title"
    image: "/assets/images/your-image.jpg"
    image_alt: "image"
    text: "Some text here."
  - title: "Another Title"
    text: "More text here."
    nav: sidebar-sample